### ISSUE TITLE
Generalize "contributor badge"

### ISSUE THREAD

**Issue by pkfrank** [forem/forem#10064]
**Is your feature request related to a problem? Please describe.**
As a Forem admin, I'd be interested in setting up an OSS contributor badge similar to the [DEV contributor badge](https://dev.to/badge/dev-contributor).  Currently, I believe its hard-coded but could be generalized.

**Describe the solution you'd like**
An ability to set my own contributor badge.  Not sure if this lives in `/admin/config` at the badge level, or elsewhere.

**Additional context**
Came out of a conversation with @benhalpern so maybe he can flesh out this issue a bit.

**Comment by ewaDev** [comment]
Hi, I would be interested in looking into this - would we expect the same image to appear? Would this badge be automatically added when a pull request is merged?

**Comment by rhymes** [comment]
Hi @ewaDev - I just realized this issue might not be relevant anymore. I'd have to ask confirmation to @juliannatetreault and @citizen428 but now that badges can be handled programmatically since #9721 I don't think we have harcoded badges anymore.

I apologize and thanks for the patience :)

**Comment by citizen428** [comment]
@rhymes There's a worker called `BadgeAchievements::BadgeAwardWorker` which calls the `BadgeRewarder` class. This iterates over a list of repositories  – which we apparently never updated to include `forem/forem` - in `award_contributor_badges_from_github` and then creates a `BadgeAchievement` for every every contributor. According to `config/schedule.yml` we still run this hourly:

```yml
award_contributor_badges_from_github:
  cron: "20 * * * *" # every hour, 20 min after the hour
  class: "BadgeAchievements::BadgeAwardWorker"
  args:
    - ""
    - award_contributor_badges_from_github
    - ""
```
