### ISSUE TITLE
Removal of env var value PRACTICALDEVELOPER_DATABASE_PASSWORD

### ISSUE THREAD

**Issue by ofhope** [forem/forem#11273]
Postgres production values don't conform to rails convention. It's also aiding malicious users in narrowing down the attack surface giving them DB name and user name. This current config makes me inclined to create a DB on my target production with the same name and user so I don't have to deviate the config. 

```
production:
  <<: *default
  database: PracticalDeveloper_production
  pool: <%= ENV['DATABASE_POOL_SIZE'] %>
  username: PracticalDeveloper
  password: <%= ENV['PRACTICALDEVELOPER_DATABASE_PASSWORD'] %>
```

I'd like to see production config conform to something like the development config. Making use of `DATABASE_URL`. 
And either making a new env variable for database name or consolidating that into the prostgres url.

```
development:
  <<: *default
  url: <%= ENV.fetch('DATABASE_URL', '') %>
  database: PracticalDeveloper_development
  variables:
      statement_timeout: <%= ENV.fetch('STATEMENT_TIMEOUT', 10_000).to_i %>
```

Or alternativly move away from DATABASE_URL and expand all the DB config into independant vars.

I'd be happy to work on this as a first issue (just set the system up locally yesterday)
