### ISSUE TITLE
A11y: provide content skip links for keyboard/screen reader users

### ISSUE THREAD

**Issue by RyKilleen** [forem/forem#1153]
**Is your feature request related to a problem? Please describe.**
When users navigate a page with keyboard tabbing, screen readers, or other assistive technology, a useful pattern is to provide a "Skip to Main Content' skip link before navigation or long lists (Tags list, etc).

**Describe the solution you'd like**
A visible skip link that pops up when a user has tabbed into an element like the nav or long tags list.

**Additional context**
https://webaim.org/techniques/skipnav/

**Comment by Link2Twenty** [comment]
This is part of the ARIA spec too 
**2.4.1 Bypass Blocks:** A mechanism is available to bypass blocks of content that are repeated on multiple Web pages. (Level A)

**Useful links:**
https://www.w3.org/TR/UNDERSTANDING-WCAG20/navigation-mechanisms-skip.html
https://www.w3.org/WAI/WCAG21/quickref/?versions=2.0&showtechniques=241#qr-navigation-mechanisms-skip

**Comment by jessleenyc** [comment]
Thanks for the feature request. This is approved if anyone wants to jump on it!

**Comment by Link2Twenty** [comment]
Just to add to this, I had to press the tab button 80 times before I could go to the first post.

**Comment by Link2Twenty** [comment]
Adding this to just before the dev logo in the nav

```html
<a href="#articles-list" class="skip-content">Skip to content</a>
```

and this to your CSS

```CSS
skip-content {
  position: absolute;
  top: 0;
  left: 50%;
  transform: translatex(-50%);
  background: black;
  color: white;
  z-index: 9999;
  padding: 12px 8px;
  cursor: default;
  pointer-events: none;
  opacity: 0;
}

skip-content:focus {
  pointer-events: auto;
  opacity: 1;
}
```
**Normal view:**
![image](https://user-images.githubusercontent.com/3534427/52788149-f871b400-3057-11e9-98ac-a7d3f46d3d81.png)
**Focused view:**
![image](https://user-images.githubusercontent.com/3534427/52788182-13dcbf00-3058-11e9-8a93-99350f9fb1fe.png)

Which is not something the everyday user would notice. But would make life, hopefully, a lot easier for keyboard users.

Thoughts?
