### ISSUE TITLE
Feature Request: Add the option to include line numbers in code blocks

### ISSUE THREAD

**Issue by Some-Dood** [forem/forem#1236]
I currently enjoy the benefits of having syntax-highlighted code blocks in my articles or comments. It makes the code stand out from the rest of the text. However, there may be times when it is necessary to reference a line number in a code block for a clearer explanation of a particular line.

In that case, I open this issue to request for an option to add line numbers in code blocks. I believe [this is possible with Jekyll](https://jekyllrb.com/docs/liquid/tags/#line-numbers)? Knowing that [Hofstadter's Law](https://en.wikipedia.org/wiki/Hofstadter%27s_law) exists, I hope that it wouldn't be too hard to implement.

Perhaps line numbers can be globally enabled through the front matter?
```markdown
---
title: Line numbers in code blocks are cool!
tags: meta
linenos: true
---
```

Or perhaps it can be enabled inline with each code block?
````markdown
---
title: Individual Code Block Activation
tags: meta
---

# Example of Unactivated Code Block
```javascript
console.log('I have no line numbers... 😟');
```

# Example of Inline Activation
```javascript linenos
console.log('I have inline line numbers! Yay! 🎉');
```
````

Perhaps it could even be globally enabled by default?

Anyway, that's pretty much this entire feature request. Looking forward to the day this becomes possible! Thanks for reading!

**Comment by Link2Twenty** [comment]
From a CSS standpoint, this would be easy to add.
Each new line would have to be wrapped somehow, personally, I'd have a `<code>` block for each line.

The CSS would need to look something like this

```css
div.highlight pre.highlight {
    counter-reset: line;
}

div.highlight pre.highlight code{
    counter-increment: line;
}

div.highlight pre.highlight code:before{
    content: counter(line) ": ";
    display: inline-block;
    text-align: right;
    width:30px;
}
```

I'm not sure how they render the blocks in the first place so I'm not sure how easy it would be to change the output template or to allow a `linenos` action.

I've taken one of your code blocks and given it line No.s with my styles

https://jsfiddle.net/link2twenty/6z47pnd9/

**Comment by Some-Dood** [comment]
@Link2Twenty I have to admit that this is **really** interesting. I have some minor changes to the selector in line 9 that I think makes the code block look a bit cleaner, if you will.

```css
div.highlight pre.highlight code:before {
  /* I removed the colon here. */
  content: counter(line) "  ";
  display: inline-block;
  text-align: right;
  /*
    I changed the text color so that it blends a bit more
    with the code block. That way, it becomes more
    subtle to the eye.
  */
  color: #555;
  width: 38px;
}
```

_P.S. I never knew that a CSS_ [`counter-increment`](https://developer.mozilla.org/en-US/docs/Web/CSS/counter-increment) _property existed. Thanks for the tip!_
