### ISSUE TITLE
DatabaseCleaner is not a fan of Docker

### ISSUE THREAD

**Issue by ChaelCodes** [forem/forem#12600]
**Describe the bug**

Attempting to run an rspec test through Docker fails with a complaint from DatabaseCleaner.

**To Reproduce**

1. Use `docker-compose up --build` to create a docker environment
1. Call `docker exec forem_rails bundle exec rspec spec/liquid_tags/twitch_tag_spec.rb`

Alt steps:
1. Use `docker-compose up --build` to create a docker environment
1. Call `docker exec -it forem_rails bash`
1. Call `bundle exec rspec spec/liquid_tags/twitch_tag_spec.rb` inside the docker container.

**Expected behavior**

The spec runs and fails or succeeds based on the RSpec.

**Screenshots**

![image](https://user-images.githubusercontent.com/8124558/107082184-cff1a000-67c1-11eb-8dc8-1411cf689c2e.png)

**Desktop (please complete the following information):**

- OS, version: Windows
- Browser, version: Chrome

**Additional context**
- [Database Cleaner](https://github.com/DatabaseCleaner/database_cleaner#safeguards)

**Comment by ChaelCodes** [comment]
Adding `DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL: "true"` to the environment of rails in docker-compose.yml did not help. It resulted in the following error.
![image](https://user-images.githubusercontent.com/8124558/107088029-57431180-67ca-11eb-9028-a60f6cffe4e2.png)

**Comment by bntzio** [comment]
I can reproduce this as well, I tried attaching to the container `docker exec -it forem_rails sh` and then ran:

```sh
DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL=true bundle exec rspec spec/system/authentication/user_logs_in_with_email_spec.rb
```

Got same error as @ChaelCodes.

**Comment by nickytonline** [comment]
Just looking into this @bntzio and @ChaelCodes.

**Comment by nickytonline** [comment]
I'm still digging into this, but one thing is apparent. There is no test environment at all. If you look at docker-composer.yml, RAILS_ENV in all containers is always development, so you never end up with a test database.

Also, setting `RAILS_ENV=test` explicitly is not necessary. It gets set when an rspec test runs since all tests import `rails_helper.rb`

https://github.com/forem/forem/blob/11d85f75c7741362d5e5e5e29d84f5f2f0081f00/spec/rails_helper.rb#L1

e.g.

https://github.com/forem/forem/blob/11d85f75c7741362d5e5e5e29d84f5f2f0081f00/spec/models/feedback_message_spec.rb#L1-L56

In regards to the remove DB URL, I believe that would be resolved with a test environment that includes a test DB.

I started looking at this by simply duplicating all the containers required to get a test environment up as a proof of concept, but that will slow down a Docker build when running `docker-compose up` which runs in `bin/container-setup`. @jdoss, instead of duplicating containers like `rails` to `rails_test`, is there a way in the rails container to be able to access the test or dev DB? Would it be another dependency in docker-compose.yml? e.g. not exactly this, but something like it?

```yml
  rails:
    image: quay.io/forem/forem:development
    container_name: forem_rails
    user: root
    ports:
      - "3000:3000"
    depends_on:
      - bundle
      - db
      - db_test
      - elasticsearch
      - redis
      - yarn
      
  ...
  
  db:
    image: postgres:11-alpine
    container_name: forem_postgresql
    environment:
      POSTGRES_USER: forem
      POSTGRES_PASSWORD: forem
      POSTGRES_DB: PracticalDeveloper_test
    ports:
      - "5433:5433"
    volumes:
      - db_data:/var/lib/postgresql/data:delegated  
```
