### ISSUE TITLE
Dashboard posts list style

### ISSUE THREAD

**Issue by atapg** [forem/forem#14017]
It's not a big deal but I'm a little bit sensitive to this kind of things. The posts list doesn't have border-radius as like as the parent does.

![dev to-ata-parvin-ghods](https://user-images.githubusercontent.com/63250900/122649145-c6018580-d141-11eb-9b98-9893042eb13b.png)

I guess this code will fix the problem =)

```css
.crayons-card:last-child{
   border-bottom-left-radius: inherit;
   border-bottom-right-radius: inherit;
}

.crayons-card:first-child{
   border-top-left-radius: inherit;
   border-top-right-radius: inherit;
}
```
