### ISSUE TITLE
Tab widths in Analytics Dashboard

### ISSUE THREAD

**Issue by yheuhtozr** [forem/forem#15873]
**Describe the bug**

The analytics period selection tabs in the analytics page (`app/views/shared/_stats.html.erb`) would have line break at spaces or hyphens, if translated text should contain them. What is worse, it will break every single character in break-anywhere languages,

**To Reproduce**

Supply translation to each tab's text and `data-text`. For example,

```yml
      period:
        aria_label: Analytics period
        week: Week this
        month: Month-ly
        infinity: 锟斤拷
```

See the screenshot.

**Expected behavior**

For the convenience of i18n alone, an obvious solution is to change the following line from `min-content` to `max-content`, then each tab's text will be contained in one line.

https://github.com/forem/forem/blob/c7902a32611ab8b342e70a80112184114ba75cba/app/assets/stylesheets/dashboard.scss#L267

But why is this rule introduced and what does it serve for? To what extent is this an expected design?

**Screenshots**

![image](https://user-images.githubusercontent.com/84892012/147310014-cbae58cd-b0f8-4700-a853-06e0f9792735.png)

**Desktop (please complete the following information):**

- OS, version: Windows 10
- Browser, version: Chrome 96
