### ISSUE TITLE
Missing title in Stack Overflow Embed

### ISSUE THREAD

**Issue by benhalpern** [forem/forem#16225]
**Describe the bug**

I noticed that the Stack Overflow liquid tag is missing a title on this post:

https://dev.to/twitterdev/getting-the-follower-count-from-twitter-api-v2-4jh6

**To Reproduce**

- Go to `/new` locally
- Paste this and preview `{% stackoverflow 70779246 %}`

**Expected behavior**

The title shows up

**Screenshots**

<img width="649" alt="Screen Shot 2022-01-20 at 10 21 33 AM" src="https://user-images.githubusercontent.com/3102842/150367955-a184ea8a-00d0-414c-9b59-789b9c2ff849.png">

**Additional context**
This won't be "fixed" in prod until the post is re-saved.

**Comment by sabarish98** [comment]
Hi folks, I can work on this, could you please assign it to me??

**Comment by citizen428** [comment]
Thanks @sabarish98, assigned it to you.

**Comment by sabarish98** [comment]
@citizen428 : While running Rspec, it shows this error, any workarounds for this:

```
[root@60134919d542 forem]# bundle exec rspec spec/liquid_tags/stackexchange_tag_spec.rb

An error occurred while loading ./spec/liquid_tags/stackexchange_tag_spec.rb.
Failure/Error: ActiveRecord::Migration.maintain_test_schema!

ActiveRecord::ConnectionNotEstablished:
  could not connect to server: Connection refused
  	Is the server running on host "localhost" (127.0.0.1) and accepting
  	TCP/IP connections on port 5432?
  could not connect to server: Cannot assign requested address
  	Is the server running on host "localhost" (::1) and accepting
  	TCP/IP connections on port 5432?
# ./spec/rails_helper.rb:43:in `<top (required)>'
# ./spec/liquid_tags/stackexchange_tag_spec.rb:1:in `require'
# ./spec/liquid_tags/stackexchange_tag_spec.rb:1:in `<top (required)>'
# /usr/share/gems/gems/bundler-2.2.22/libexec/bundle:49:in `block in <top (required)>'
# /usr/share/gems/gems/bundler-2.2.22/libexec/bundle:37:in `<top (required)>'
# ------------------
# --- Caused by: ---
# PG::ConnectionBad:
#   could not connect to server: Connection refused
#   	Is the server running on host "localhost" (127.0.0.1) and accepting
#   	TCP/IP connections on port 5432?
#   could not connect to server: Cannot assign requested address
#   	Is the server running on host "localhost" (::1) and accepting
#   	TCP/IP connections on port 5432?
#   ./spec/rails_helper.rb:43:in `<top (required)>'
No examples found.


Finished in 0.00019 seconds (files took 7 minutes 21 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples
```
I am using the docker setup. I executed the spec from within the container

**Comment by citizen428** [comment]
This just means your local Postgres database is not running. On Travis we actually see a different error related to the escaping of the string.

**Comment by sabarish98** [comment]
Yes, @citizen428 , I saw that it was escaping of strings from the logs on Travis. I wanted to verify it, so tried running it on my local to check it once.

@djuber : Please do let me know how to run tests on container setup

**Comment by djuber** [comment]
Hi @sabarish98 

I think the issue you're seeing trying to run rspec is that the docker setup for development has a single database (PracticalDeveloper_development) configured, but no test db:

https://github.com/forem/forem/blob/main/docker-compose.yml#L114-L124
https://github.com/forem/forem/blob/main/config/database.yml#L61-L70

```
# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL_TEST", "postgres:///Forem_test") %>
  database: <%= ENV.fetch("DATABASE_NAME_TEST", "Forem_test") %><%= ENV["TEST_ENV_NUMBER"] %>
  variables:
      statement_timeout: <%= ENV.fetch("STATEMENT_TIMEOUT", 10_000).to_i %>
```


The test setup is looking for a test db, when it can't find one passed in as an environment variable (`DATABASE_URL_TEST` and `DATABASE_NAME_TEST`), it uses the .env file, which probably looks like mine:

```
DATABASE_NAME_TEST=Forem_test
# Differentiate test db from dev db. Test DB is wiped on each test run.
DATABASE_URL_TEST="postgresql://localhost:5432/Forem_test"
```


---- 

## Workaround by adding this db

One option would be to add a new host to the docker-compose setup like this and add a second env var to the rails container (depends_on: testdb and the DATABASE_URL_TEST env vars are changed in the rails container block):

```
services:
  rails:
    image: quay.io/forem/forem:development
    container_name: forem_rails
    user: root
    ports:
      - "3000:3000"
    depends_on:
      - bundle
      - db
      - testdb
      - redis
      - yarn
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgresql://forem:forem@db:5432/PracticalDeveloper_development
      DATABASE_URL_TEST: postgresql://forem:forem@testdb/Forem_test
      REDIS_SESSIONS_URL: redis://redis:6379
      REDIS_SIDEKIQ_URL: redis://redis:6379
      REDIS_URL: redis://redis:6379
      RACK_TIMEOUT_WAIT_TIMEOUT: 10000
      RACK_TIMEOUT_SERVICE_TIMEOUT: 10000
      STATEMENT_TIMEOUT: 10000
      APP_DOMAIN: localhost:3000
    volumes:
      - .:/opt/apps/forem:delegated
    entrypoint: ["dockerize", "-wait", "tcp://db:5432", "-wait", "tcp://redis:6379", "-wait", "file:///opt/apps/forem/vendor/bundle/.bundle_finished", "-timeout", "2700s", "-wait-retry-interval", "10s"]
    command: [ "bash", "-c", "./scripts/entrypoint.sh bootstrap && bundle exec rails server -b 0.0.0.0 -p 3000"]

  # new container running postgresql for tests (separate from development db):
  testdb:
    image: postgres:13-alpine
    container_name: forem_postgresql_test
    environment:
      POSTGRES_USER: forem
      POSTGRES_PASSWORD: forem
      POSTGRES_DB: Forem_test
    expose:
      - "5432"
    volumes:
      - db_data_test:/var/lib/postgresql/data:delegated

  # add a volume for the test db (probably not needed if you don't need persistence)
  volumes:
    db_data:
    db_data_test:
```

With those changes in place I'm able to run rspec tests in the container (after setting up the db):

```
$ docker-compose run rails /bin/bash
Starting forem_redis           ... done
Starting forem_yarn            ... done
Starting forem_postgresql      ... done
Starting forem_bundle          ... done
Starting forem_postgresql_test ... done
Creating forem-docker_rails_run ... done
2022/01/25 15:21:47 Waiting for: tcp://db:5432
2022/01/25 15:21:47 Waiting for: tcp://redis:6379
2022/01/25 15:21:47 Waiting for: file:///opt/apps/forem/vendor/bundle/.bundle_finished
2022/01/25 15:21:47 Connected to tcp://redis:6379
2022/01/25 15:21:47 Connected to tcp://db:5432
2022/01/25 15:21:57 File file:///opt/apps/forem/vendor/bundle/.bundle_finished had been generated

[root@a0ea5615ab0f forem]# DISABLE_SPRING=1 RAILS_ENV=test bin/rails db:drop db:create db:schema:load 
Dropped database 'Forem_test'
Created database 'Forem_test'
WARNING: sqlite and mysql triggers may not be shared by multiple actions

[root@a0ea5615ab0f forem]# bundle exec rspec spec/liquid_tags/stackexchange_tag_spec.rb 
[Zonebie] Setting timezone: ZONEBIE_TZ="Atlantic Time (Canada)"
....

Finished in 2.69 seconds (files took 3.22 seconds to load)
4 examples, 0 failures
```

There are currently some limitations - capybara tests that rely on chrome headless (where `type: :system, js: true` is set) I don't think work at all, but basic rspec tests relying on the db and ruby code (including request tests) _should_ work.
