### ISSUE TITLE
Allow photo credit attribution for cover_image

### ISSUE THREAD

**Issue by WesSouza** [forem/forem#1849]
It is common practice to add credits to pictures used in articles. I'd propose adding more properties to FrontMatter so that a `<figcaption>` element is added below the photo.

**Describe the solution you'd like**

```yaml
cover_image: https://cdn-images-1.medium.com/max/1024/1*NQRv_y3HIXXvCOt5UWLjzQ.jpeg
cover_image_credit_text: Photo by John Smith
cover_image_credit_url: https://example.org/
```

**Describe alternatives you've considered**
I'm using the end of my post for the attribution, but that's not ideal IMO.

**Additional context**
<img width="925" alt="screen shot 2019-02-22 at 5 53 15 pm" src="https://user-images.githubusercontent.com/126160/53275893-d79a0600-36ca-11e9-9673-d4cbb07a0a9c.png">
