### ISSUE TITLE
Allow "key links" section to be defined in some non-hardcoded way

### ISSUE THREAD

**Issue by benhalpern** [forem/forem#4661]
Currently we have a couple "key links" areas. (left sidebar on home page, site footer, key links page.

They do not all show all the links (should they?). Either way, we should be able to define what these links are at the app level, both for generalization purposes and also possibly for dev.to administration simplification.

I'm not sure what the right implementation for this is.

**Comment by bolariin** [comment]
Are you considering using a file for generalization? If you are considering representing the information in a file, you could use a yaml file. With a yaml file, you can represent both lists and key value pairs.

```yml
links:
  - title: About
    link: /about
  - title: Sponsors
    link: /sponsors
````
