### ISSUE TITLE
hover profile view on posts

### ISSUE THREAD

**Issue by Bhupesh-V** [forem/forem#4745]
**Is your feature request related to a problem? Please describe.**

Currently we do not have any hover profile view for posts on dev

![Screenshot at 2019-11-07 19-36-10](https://user-images.githubusercontent.com/34342551/68395660-2d99d580-0196-11ea-8dd4-d6ff9dcd41c6.png)

**Describe the solution you'd like**
We could do this like github

![profile](https://user-images.githubusercontent.com/34342551/68395883-98e3a780-0196-11ea-92f9-24da8b249f77.png)

We can display their bio, location etc.
Instead of *Member of BitPlease* (as shown in screenshot) we could show all social links a user has on his/her DEV Profile

**Comment by aligoren** [comment]
I did something using the Chrome developer console.

![image](https://user-images.githubusercontent.com/4205423/68765244-640ba080-062d-11ea-96b7-b5e7e5a52100.png)

I created a `div.profile-card` under the `header#main-title`.

**For instance**

Full HTML & CSS

```css
.profile-card {
    width: 35ch;
    border: 1px solid #c3c3c3;
    padding: 2ch;
    box-shadow: 2px 2px #d3d3d3 !important;
    position: absolute;
    background-color: #fff;
    border-radius: 0.2em;
    height: 15vh;
}

.card-span {
   font-size: 0.8em;
    font-weight: 800;
    margin-bottom: 2px;
    color: #666666;
}

.card-inner {
 position: absolute;
    top: 0ch;
    left: 5em;
}
```

```html

<div class="profile-card">
    <img class="profile-pic" src="https://res.cloudinary.com/practicaldev/image/fetch/s--UQOW0ass--/c_fill,f_auto,fl_progressive,h_50,q_auto,w_50/https://thepracticaldev.s3.amazonaws.com/uploads/user/profile_image/54900/e37fbc73-e4a3-4997-a747-6b3251d3877e.jpeg" alt="olistik profile image">

    <div class="card-inner">
       <p> <span class="card-span">@olistik</span></p>
       <p><span class="card-span">OMG it's full of patterns.</span></p>
       <p><span class="card-span">work</span> Developer at StreetLib</p>
       <p><span class="card-span">location</span> Desio, Italy.</p>
       <p><span class="card-span">joined</span> Jan 23, 2018.</p>
    </div>

</div>
```
