### ISSUE TITLE
Reactions pane partially overlaps sidebar on Android

### ISSUE THREAD

**Issue by mzaini30** [forem/forem#9362]
![Screenshot_2020-07-17-06-43-55-32](https://user-images.githubusercontent.com/7939342/87729983-2d5bda80-c7f9-11ea-9473-7ddf3db75550.png)

**My smartphone**

- OS: Android 
- Realme C2
- Browser: Chrome

**Comment by citizen428** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @forem/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/forem/forem/blob/master/CONTRIBUTING.md).

**Comment by Link2Twenty** [comment]
I believe this is mobile in general not just android. It's caused by `crayons-article-actions` being `position: fixed;`.
A simple solution would be to increase padding bottom of `crayons-footer` by the 56px. Though you would only want to do this on a page where the article actions appear.

Something like this:
```css
.crayons-footer {
  --footer-padding: var(--su-4);
  background: var(--footer-bg);
  color: var(--footer-color);
  padding-top: var(--footer-padding);
  padding-bottom: calc(var(--footer-padding) + 56px);

  @media (min-width: $breakpoint-m) {
    --footer-padding: var(--su-6);
    padding-bottom: var(--footer-padding);
  }

  @media (min-width: $breakpoint-l) {
    --footer-padding: var(--su-8);
    padding-bottom: var(--footer-padding);
  }
}
```

An alternative solution would be to move `crayons-layout__sidebar-left,` in the dom, to just after `crayons-layout__content grid` and set it to be [position sticky](https://caniuse.com/#feat=css-sticky) with a bottom of 0. Also remove position fixed from `crayons-article-actions`.

Here's a quick 5 minute hack to show it working
![dev-to__position-sticky](https://user-images.githubusercontent.com/3534427/89720631-1eb5ad00-d9cc-11ea-89b3-305136132369.gif)
