### ISSUE TITLE
Disable issue workflow for collaborators and members for forem/forem

### ISSUE THREAD

**Issue by abenerd** [forem/forem#9800]
**Is your feature request related to a problem? Please describe.**

As I understand it the issue workflow is for contributors of the project the tell them what they can expect on how their issue will be handled, this is great for new and returning contributors but I think it can be annoying for the collaborators and members of `forem`  team. They know the workflow and do not be inundated with emails and notifications when they open an issue in their own repository. 
**Describe the solution you'd like**

Add a condition on when the workflow is supposed to run like.
One would have to decide for what kind of association the workflow should be skipped as I don't know how the `forem` team is organized internally.
```yaml
- if: github.event.issue.author_association != 'OWNER' && github.event.issue.author_association != 'COLLABORATOR'
  name: Automatic Comment
  uses: peter-evans/create-or-update-comment@v1
  with:
    issue-number: ${{ github.event.issue.number }}
    body: The message
```
**Describe alternatives you've considered**

**Additional context**
https://docs.github.com/en/graphql/reference/enums#commentauthorassociation
